### ISSUE TITLE
Engineering team to share Github container image repo

### ISSUE THREAD

**Issue by tsunamit** [mlcommons/modeltune#72]
Context doc: https://docs.google.com/document/d/1q1UPz9I_Hzft6-sS24P2TVKq6Ov7ghp-LRyVLS9rfFo/edit

**Comment by wpietri** [comment]
Hi, Ryan! I'd suggest we just use the mlcommons one: https://github.com/orgs/mlcommons/packages

More details here: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

If you don't have permission to push to that, I think support can help you out.

I'd also like if it the Dockerfiles are checked in somewhere visible to us (e.g., in modeltune) to aid in debugging if there are problems.
